ServerEvents.recipes(event => {
event.remove({output: 'sophisticatedbackpacks:magnet_upgrade'})
event.remove({output: 'sophisticatedbackpacks:advanced_magnet_upgrade'})
event.remove({output: 'sophisticatedbackpacks:feeding_upgrade'})
event.remove({output: 'sophisticatedbackpacks:advanced_feeding_upgrade'})
event.remove({output: 'sophisticatedbackpacks:inception_upgrade'})
event.remove({output: 'sophisticatedbackpacks:smelting_upgrade'})
event.remove({output: 'sophisticatedbackpacks:auto_smelting_upgrade'})
event.remove({output: 'sophisticatedbackpacks:smoking_upgrade'})
event.remove({output: 'sophisticatedbackpacks:auto_smoking_upgrade'})
event.remove({output: 'sophisticatedbackpacks:blasting_upgrade'})
event.remove({output: 'sophisticatedbackpacks:auto_blasting_upgrade'})
event.remove({output: 'sophisticatedbackpacks:stonecutter_upgrade'})
event.remove({output: 'sophisticatedbackpacks:crafting_upgrade'})
event.remove({output: 'sophisticatedbackpacks:stack_upgrade_tier_4'})
event.remove({output: 'sophisticatedbackpacks:stack_upgrade_tier_3'})
event.remove({output: 'sophisticatedbackpacks:stack_upgrade_tier_2'})
})